---
# tasks file for update-packages
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install dnf-automatic
  dnf:
    name: dnf-automatic
    state: present

- name: Ensure service yum-cron(dnf-automatic-install.timer) is running and enabled on boot
  service:
    name: dnf-automatic-install.timer
    state: started
    enabled: yes
    
- name: List Files in a folder
  command: ls -l > /tmp/test-hook.txt 
    
