---
# tasks file for firewalld

  - name: install the latest version of firewalld
    yum:
      name: firewalld
      state: latest


  - name: Ensure Firewalld is started
    systemd:
        name: firewalld
        state: started
        enabled: true


  - name: Firewalld to open the required port
    firewalld:
      port: 8080/tcp
      permanent: yes
      immediate: yes
      state: enabled
      zone: public

    

